### ISSUE TITLE
Demo import

### ISSUE THREAD

**Issue by benedettogit** [precisethemes/courtyard#2]
I'm unable to import demo data, 

New AJAX call!
[ERROR] Failed to import "pexels-photo-90317" (Media)
[ERROR] Failed to import "pexels-photo-164595" (Media)
[ERROR] Failed to import "bed-bedroom-room-furniture" (Media)
[ERROR] Failed to import "pexels-photo-189293" (Media)
[ERROR] Failed to import "cy" (Media)
[ERROR] Failed to import "logo" (Media)
[ERROR] Failed to import "bedroom-architectural-interior-lifestyle-53603" (Media)
[ERROR] Failed to import "pexels-photo-97083" (Media)
[ERROR] Failed to import "pexels-photo-129062" (Media)
[ERROR] Failed to import "pexels-photo-29683" (Media)

is there a way i can upload those images manually?

**Comment by suvanno** [comment]
Hello @benedettogit 
There might be another way to upload images manually, i.e we can provide you to download link for all attached images but we would like to fix this issue so that it will be easy for you and other users.
We will inform you shortly after fixing the issue.

Thanks for reporting the issue.

**Comment by suvanno** [comment]
Hello
Please download the latest theme from [WordPress.org](https://wordpress.org/themes/courtyard/)
I just tested it and there is no any issue on importing demo data.

Let us know if you still getting same issues. We do have support services at [https://precisethemes.com/support/](https://precisethemes.com/support/)

Thanks

**Comment by benedettogit** [comment]
I've downloaded from your link, and made a test, but still the same 

New AJAX call!
[ERROR] Failed to import "pexels-photo-90317" (Media)
[ERROR] Failed to import "pexels-photo-164595" (Media)
[ERROR] Failed to import "bed-bedroom-room-furniture" (Media)
[ERROR] Failed to import "pexels-photo-189293" (Media)
[ERROR] Failed to import "cy" (Media)
[ERROR] Failed to import "logo" (Media)
[ERROR] Failed to import "bedroom-architectural-interior-lifestyle-53603" (Media)
[ERROR] Failed to import "pexels-photo-97083" (Media)
[ERROR] Failed to import "pexels-photo-129062" (Media)
[ERROR] Failed to import "pexels-photo-29683" (Media)
[ERROR] Failed to import "photo-1473233549235-59a9de4c2cc1" (Media)

but from your link i see Last updated: May 7, 2017
